apiVersion : apps/v1
kind: Deployment
metadata:
  name: tvanschijndelpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvanschijndelpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: tvanschijndelpipelinesjavascriptdocker 
    spec:
      containers:
        - name: tvanschijndelpipelinesjavascriptdocker 
          image: networkcontainerregistry.azurecr.io/tvanschijndelpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
